version: '3.7'

services:

    dev:
        image: affluences/display:dev
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '4200:4200'
